apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-rust-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /rust
        pathType: Prefix
        backend:
          service:
            name: app-rust-service
            port:
              number: 8001
